project:
  type: book

book:
  title: "WJP - R Coding Handbook"
  author: "Carlos A. Toruño P."
  date: "October, 2022"
  chapters:
    - index.qmd
    - workflow.qmd
    - coding.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual

